### ISSUE TITLE
[Release One] If enter undefined user-utterence while creating story,It is not displaying informative error.

### ISSUE THREAD

**Issue by karishmabodhane** [navigateconsulting/virtual-assistant#100]
| Attributes|      Values|
|----------|:-------------:|
| Detected By |  @karishmabodhane  | 
| Detected On |   15/07/2019   |  
| Detected in Release | One |  
| Severity |Medium  |
| Priority |Medium |
| Module | Manage Stories|   
| Estimated Fix Time |  |
| Root Cause Analysis|  |     
| Actual Fix Time |  |  
| Closing Date |  |
| Closing Version |  |    
| Planed Closing Version | | 

**Description**

**Pre-Condition:** User should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Launch EVA ChatbotApp URL.
2. Create a project.
3. Create a domain inside projectv with some intent and response.
4. Create a story, try to add undefined intent or response.

**Expected Result:** If user try to enter undefined intent or respnse then Eva should display a informative message .

**Actual Result:** Eva is not displating any informative message it only changing the color of node.

![image](https://user-images.githubusercontent.com/47655741/61207123-e7fe5c00-a711-11e9-8596-4be2a23bd34c.png)

**Comment by saikiran2603** [comment]
Issue fixed
