### ISSUE TITLE
[Release One] Able to navigate away from the story description page with response not being mapped to any intent

### ISSUE THREAD

**Issue by karishmabodhane** [navigateconsulting/virtual-assistant#105]
| Attributes|      Values|
|----------|:-------------:|
| Detected By |  @karishmabodhane  | 
| Detected On |   18/07/2019   |  
| Detected in Release | One |  
| Severity |High  |
| Priority |High |
| Module | Manage Story|   
| Estimated Fix Time |  |
| Root Cause Analysis|  |     
| Actual Fix Time |  |  
| Closing Date |  |
| Closing Version |  |    
| Planed Closing Version | | 

**Description**

**Pre-Condition:** User should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Launch EVA ChatbotApp URL.
2. Create an intent, response, entity
3. Create a story and map the intent to the response with annotated entity
4. Delete the intent node.
5. Navigate away from the story page

**Expected Result:** User should not be allowed to navigate away from the story page when the response is not mapped to an intent

**Actual Result:** User is able to navigate away from the story page without mapping the response to an intent.

![image](https://user-images.githubusercontent.com/47655741/61453242-3bbfae00-a97b-11e9-999b-38e9ff677111.png)

**Comment by saikiran2603** [comment]
Issue fixed
