### ISSUE TITLE
[Release One]Not able to do free search in filter intent.

### ISSUE THREAD

**Issue by karishmabodhane** [navigateconsulting/virtual-assistant#118]
| Attributes|      Values|
|----------|:-------------:|
| Detected By |  @karishmabodhane  | 
| Detected On |   19/08/2019   |  
| Detected in Release | One |  
| Severity |Medium  |
| Priority |Medium |
| Module | Manage Intents|   
| Estimated Fix Time |  |
| Root Cause Analysis|  |     
| Actual Fix Time |  |  
| Closing Date |  |
| Closing Version |  |    
| Planed Closing Version | | 

**Description**

**Pre-Condition:** User should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Launch EVA ChatbotApp URL.
2. Create a project and a domain.
3. Create intent inside the domain.
4. Add some user utterances.
5. Search for the user utterances, which was created in step no 4 but by changing the case of letters.

**Expected Result:** User should be able able to do a free text search.

**Actual Result:** User is not able to search for intent values if he changes the case of letters.

Before search:
![image](https://user-images.githubusercontent.com/47655741/63242610-93e91900-c275-11e9-936e-218e0979427e.png)

Searching for a business visa that is present in all the user utterances:
![image](https://user-images.githubusercontent.com/47655741/63242673-cabf2f00-c275-11e9-9ff9-e98e622f6d38.png)

**Comment by nishant1712** [comment]
This issue is fixed. Free intent text search has now been implemented.
