### ISSUE TITLE
[Release One]Entering a same query two time on single click.

### ISSUE THREAD

**Issue by karishmabodhane** [navigateconsulting/virtual-assistant#121]
Attributes|      Values|
|----------|:-------------:|
| Detected By |  @karishmabodhane  | 
| Detected On |   20/08/2019   |  
| Detected in Release | One |  
| Severity |Medium  |
| Priority |Medium |
| Module | Manage EVA|   
| Estimated Fix Time |  |
| Root Cause Analysis|  |     
| Actual Fix Time |  |  
| Closing Date |  |
| Closing Version |  |    
| Planed Closing Version | | 

**Description**

**Pre-Condition:** User should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Launch EVA ChatbotApp URL.
2. Create a project with all the required data to train the bot.
3. Train the bot 
4. Click on "try it now" icon.
5. Enter user utterance which is not defined in the project.
6. Enter user utterance which is defined in the project.

**Expected Result:** On a single hit it should enter query only one time.
**Actual Result:** Able to add the same query on a single enter.

![image](https://user-images.githubusercontent.com/47655741/63347587-05f45780-c375-11e9-827c-6a8a41ca26fb.png)
![image](https://user-images.githubusercontent.com/47655741/63347711-4bb12000-c375-11e9-9a97-129a4a582889.png)

**Comment by saikiran2603** [comment]
Resolved now
