### ISSUE TITLE
[Release One]Unable to train large projects.

### ISSUE THREAD

**Issue by karishmabodhane** [navigateconsulting/virtual-assistant#122]
| Attributes|      Values|
|----------|:-------------:|
| Detected By |  @karishmabodhane  | 
| Detected On |   26/08/2019   |  
| Detected in Release | One |  
| Severity |High  |
| Priority |High |
| Module | Manage Project|   
| Estimated Fix Time |  |
| Root Cause Analysis|  |     
| Actual Fix Time |  |  
| Closing Date |  |
| Closing Version |  |    
| Planed Closing Version | | 

**Description**

**Pre-Condition:** User should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Launch EVA ChatbotApp URL.
2. Perform try it now functionality for a project, which has a large amount of data.

**Expected Result:** "Try Now" functionality should work well for large data.

**Actual Result:**"Try Now" functionality is not working well for large data .

**Comment by saikiran2603** [comment]
Resolved in master branch now.
