### ISSUE TITLE
[Release One][intermittent issue] Breadcrumb is not working.

### ISSUE THREAD

**Issue by karishmabodhane** [navigateconsulting/virtual-assistant#127]
| Attributes|      Values|
|----------|:-------------:|
| Detected By |  @karishmabodhane  | 
| Detected On |   11/09/2019   |  
| Detected in Release | One |  
| Severity |Medium  |
| Priority |Medium |
| Module | Manage Eva|   
| Estimated Fix Time |  |
| Root Cause Analysis|  |     
| Actual Fix Time |  |  
| Closing Date |  |
| Closing Version |  |    
| Planed Closing Version | | 

**Description**

**Pre-Condition:** Users should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Launch EVA ChatbotApp URL.
2. select a project and then domain.
3. Click on the story tab and enter into a story.
4. Try to come back to the story tab with the help of breadcrumbs.

**Expected Result:** Users should be able to back from a story into the story tab with the help of breadcrumbs.

**Actual Result:** Not able to come back from the story into a story tab.

Before:
![image](https://user-images.githubusercontent.com/47655741/64670524-11720480-d483-11e9-96a1-bce4f1973f7a.png)

After click on a story part of breadcrumbs:
![image](https://user-images.githubusercontent.com/47655741/64670554-2d75a600-d483-11e9-8374-3b3a2bd229f7.png)

**Comment by saikiran2603** [comment]
resolved
