### ISSUE TITLE
[Release One]Fetching a wrong error message "Entity used in an intent" on the deletion of an unmapped entity.

### ISSUE THREAD

**Issue by karishmabodhane** [navigateconsulting/virtual-assistant#128]
| Attributes|      Values|
|----------|:-------------:|
| Detected By |  @karishmabodhane  | 
| Detected On |   18/09/2019   |  
| Detected in Release | One |  
| Severity |Medium |
| Priority |Medium |
| Module | Manage Entity|   
| Estimated Fix Time |  |
| Root Cause Analysis|  |     
| Actual Fix Time |  |  
| Closing Date |  |
| Closing Version |  |    
| Planed Closing Version | | 

**Description**

**Pre-Condition:** Users should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Launch EVA ChatbotApp URL.
2. Create a project and a domain inside the project.
3. create an entity
4. create intents and annotate entity with intents.
5. Now remove annotation and try to delete entity.

**Expected Result:** If the entity is not mapped with any intent then it should not fetch an error message like"Entity is used in an intent".

**Actual Result:** fetching a wrong error message.

![image](https://user-images.githubusercontent.com/47655741/65121931-a342ba00-da0d-11e9-9cda-2cc5d7f826e0.png)

**Comment by nishant1712** [comment]
This issue has been fixed.
