### ISSUE TITLE
[Release One]After the opening of the entity slide window, everything should get disabled other than the entity pane.

### ISSUE THREAD

**Issue by karishmabodhane** [navigateconsulting/virtual-assistant#130]
| Attributes|      Values|
|----------|:-------------:|
| Detected By |  @karishmabodhane  | 
| Detected On |   24/09/2019   |  
| Detected in Release | One |  
| Severity |Low |
| Priority |Low |
| Module | Manage EVA|   
| Estimated Fix Time |  |
| Root Cause Analysis|  |     
| Actual Fix Time |  |  
| Closing Date |  |
| Closing Version |  |    
| Planed Closing Version | | 

**Description**

**Pre-Condition:** Users should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Launch EVA ChatbotApp URL.
2. Create a project and domain inside the project.
3. Create entities, intents, and responses.
4. Enter into a intent and click on the select entity field(entity list will open).
5. Click on the entity icon and open entity pane.

**Expected Result:** After opening the entity pane, the entity list should get disabled.

**Actual Result:** Even after opening the entity pane, the entity list is still in focus.

![image](https://user-images.githubusercontent.com/47655741/65511883-c8479900-def5-11e9-8280-686e4105cb8c.png)

![image](https://user-images.githubusercontent.com/47655741/65511911-d695b500-def5-11e9-85e7-32eced32be0f.png)

**Comment by nishant1712** [comment]
This issue has been resolved.
