### ISSUE TITLE
[Release one]Count notification circle is displaying randomly in the intent mapping page.

### ISSUE THREAD

**Issue by karishmabodhane** [navigateconsulting/virtual-assistant#132]
| Attributes|      Values|
|----------|:-------------:|
| Detected By |  @karishmabodhane  | 
| Detected On |   25/09/2019   |  
| Detected in Release | One |  
| Severity |Low  |
| Priority |Low |
| Module | Manage Entity and Intent|   
| Estimated Fix Time |  |
| Root Cause Analysis|  |     
| Actual Fix Time |  |  
| Closing Date |  |
| Closing Version |  |    
| Planed Closing Version | | 

**Description**

**Pre-Condition:** Users should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Launch EVA ChatbotApp URL.
2. Create a project and a domain inside a project.
3. Create intents and entities.
4. Go to the intent tab and select an intent.
5. Annotate a entity to the intents.

**Expected Result:** Mapped entity count notification circle should be displayed uniformly everywhere.

**Actual Result:**In some intents count notification circle is appearing at the beginning.

![image](https://user-images.githubusercontent.com/47655741/65576051-d1387900-df8e-11e9-8450-48e93bc3ba42.png)

**Comment by nishant1712** [comment]
This issue is not reproducible.
