### ISSUE TITLE
[Release One]Unable to map '&' to a entity.

### ISSUE THREAD

**Issue by karishmabodhane** [navigateconsulting/virtual-assistant#133]
| Attributes|      Values|
|----------|:-------------:|
| Detected By |  @karishmabodhane  | 
| Detected On |   25/09/2019   |  
| Detected in Release | One |  
| Severity |Medium |
| Priority |Medium |
| Module | Manage Entity and Intent|   
| Estimated Fix Time |  |
| Root Cause Analysis|  |     
| Actual Fix Time |  |  
| Closing Date |  |
| Closing Version |  |    
| Planed Closing Version | | 

**Description**

**Pre-Condition:** Users should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Launch EVA ChatbotApp URL.
2. Create a project and a domain inside a project.
3. Create intents with '&' and entities.
4. Go to the intent tab and select an intent.
5. Annotate a entity to the intent (include &).

**Expected Result:**It should allow user to map "&" to an entity.

**Actual Result:**Unable to map "&" to an entity.

![image](https://user-images.githubusercontent.com/47655741/65580531-79ead680-df97-11e9-88ac-45d3d5a041ef.png)

**Comment by nishant1712** [comment]
This issue has been resolved now. The replace calls are to trim leading and trailing white-space.
