### ISSUE TITLE
[Release One]Displaying a wrong error message in response utterances page, When there is no result found for search.

### ISSUE THREAD

**Issue by karishmabodhane** [navigateconsulting/virtual-assistant#135]
| Attributes|      Values|
|----------|:-------------:|
| Detected By |  @karishmabodhane  | 
| Detected On |   03/10/2019   |  
| Detected in Release | One |  
| Severity |Medium  |
| Priority |Medium |
| Module | Manage Response/Intents|   
| Estimated Fix Time |  |
| Root Cause Analysis|  |     
| Actual Fix Time |  |  
| Closing Date |  |
| Closing Version |  |    
| Planed Closing Version | | 

**Description**

**Pre-Condition:** Users should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Launch EVA ChatbotApp URL.
2. Create a project and create a domain inside the project.
3. Create a response/intents and add user utterances.
4. Search for such response/intent value which is not present.

**Expected Result:** It should display a message like "No result found".

**Actual Result:** displaying a message like "At least once response/intent should be defined".

Response:
Before filter:
![image](https://user-images.githubusercontent.com/47655741/66101437-775a3380-e5cc-11e9-86a1-944a6b7d4053.png)

After seach:
![image](https://user-images.githubusercontent.com/47655741/66101457-8a6d0380-e5cc-11e9-9b5d-ef30769d504b.png)

Intent:
Before filter:
![image](https://user-images.githubusercontent.com/47655741/66102448-09b00680-e5d0-11e9-8ae7-a6c97f82b3f8.png)

After search:
![image](https://user-images.githubusercontent.com/47655741/66102467-16345f00-e5d0-11e9-93de-6936fa7bc97f.png)

**Comment by nishant1712** [comment]
Issue Resolved. Different Alert messages for different scenarios.
