### ISSUE TITLE
[Release One]Refresh not working as Expected and navigates the user to HomePage

### ISSUE THREAD

**Issue by svarghese8** [navigateconsulting/virtual-assistant#14]
| Attributes|      Values|
|----------|:-------------:|
| Detected By |  @svarghese8 | 
| Detected On |   22/04/2019   |  
| Detected in Release | One |  
| Severity | High  |
| Priority | High |
| Module | Application|   
| Estimated Fix Time |  |
| Root Cause Analysis|  |     
| Actual Fix Time |  |  
| Closing Date |  |
| Closing Version |  |    
| Planed Closing Version | | 

**Description**

**Pre-Condition:** User should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Launch EVA ChatbotApp URL in Mozilla Firefox.
2. Create a User-defined Domain
3. Navigate to the Intent Page
4. Refresh the page

**Expected Result:** Page Should be refreshed and the user should return to the same page.

**Actual Result:** Page is refreshed and the User is navigated back to the Home Page

Before Refresh

![Refresh1](https://user-images.githubusercontent.com/49480607/56659250-4212f680-66ba-11e9-85b7-b13d9b7b5e48.PNG)

After Refresh

![Refresh2](https://user-images.githubusercontent.com/49480607/56659256-44755080-66ba-11e9-936f-339380f41470.PNG)

**Comment by nishant1712** [comment]
Breadcrumb provision has been given in the application. And the app being a SPA, this is how it will function.
