### ISSUE TITLE
UI Trainer build fails

### ISSUE THREAD

**Issue by EdukondaluK** [navigateconsulting/virtual-assistant#159]
Hi,

Please help me to get out of UI trainer building error.

![image](https://user-images.githubusercontent.com/18613739/72176841-5abc6b80-3405-11ea-8a6b-9da6b50f761a.png)

Thanks and Regards,
Edukondalu

**Comment by EdukondaluK** [comment]
Hi please check my logs and replay

**Comment by nishant1712** [comment]
Hi @EdukondaluK , can you please let down the devDependencies mentioned in your package.json file. Thanks

**Comment by saikiran2603** [comment]
Try removing node modules folder in ui-trainer , and build the container again . Let us know if this helps or you still facing the issue

**Comment by saikiran2603** [comment]
@EdukondaluK are you still facing this issue ?
