### ISSUE TITLE
Deployed api gate way script in cloud

### ISSUE THREAD

**Issue by EdukondaluK** [navigateconsulting/virtual-assistant#161]
Deployed app.py script into cloud as an application. it generates api and it used in the environment file for execution of front end application. But it is connecting fine and emit data is not getting. 

though everything is working fine in local (local api for app.py script).  please check and pasted logs.
received web socket is not coming when I deployed into cloud but in local received web socket and upgrade web socket messages are coming fine.
![image](https://user-images.githubusercontent.com/18613739/72718907-d3a58b00-3b9c-11ea-81d8-b3850109e648.png)

UI

![image](https://user-images.githubusercontent.com/18613739/72719043-1f583480-3b9d-11ea-9168-656b9f5ef20c.png)

**Comment by saikiran2603** [comment]
Deploy all the containers in cloud and use the compose file to get the containers up. This way the containers are accessible over network and would be able to communicate. What seems to be the issue with your deployment is , api gateway and the ui are not able to communicate.

**Comment by EdukondaluK** [comment]
it is working fine in local.
mongo db is our database has been provided.

from aiohttp import web
import socketio
from config import CONFIG


#if CONFIG.get('api_gateway', 'LOGGING') == 'TRUE':
    #print("--------------------Starting Socketio Connection in Debug Mode --------------------------")

sio = socketio.AsyncServer(async_mode='aiohttp', logger=True, engineio_logger=True, ping_timeout=60000000, ping_interval=6000000,cors_allowed_origins="*")

#else:
 #   sio = socketio.AsyncServer(async_mode='aiohttp', logger=False, engineio_logger=False, ping_timeout=60000000, ping_interval= 6000000)

app = web.Application()
sio.attach(app)


async def index(request):
    print(request)
    with open('index.html') as f:
        return web.Response(text=f.read(), content_type='text/html')

print("rasa backend")
# Imports for Endpoints

import endpoints
import rooms_endpoints

print("back backend")

app.router.add_get('/', index)

# We kick off our server
if __name__ == '__main__':
    sio.attach(app)
    web.run_app(app)

**Comment by saikiran2603** [comment]
which containers are on prem and which are on cloud ?

**Comment by EdukondaluK** [comment]
it is mongo database access issues
