### ISSUE TITLE
UI trainer build pack fails

### ISSUE THREAD

**Issue by EdukondaluK** [navigateconsulting/virtual-assistant#164]
everything is working in local the angular app.
have did build and pushed to my cloud there  am facing issues.

it has sync or should connect backend url (app url) but it is failing in front end it self.

![image](https://user-images.githubusercontent.com/18613739/76427800-cc4b7280-63d2-11ea-939c-de5e987e64cf.png)

please check is it build fails in UI?

please ping me your gmail account so that will touch with you fr only UI trainer.
am not much expert in angular code.

Thanks and Regards,
Edukondalu
+91 8308762655

**Comment by saikiran2603** [comment]
There was some change for angular proxy , the fixed has been pushed to master could you check if this issue has been resolved now ?

**Comment by saikiran2603** [comment]
Hi , This issue has been fixed. Could you check it and let us know if this works as expected now ?
