### ISSUE TITLE
Wrong dependencies for python at install (Rasa 1.8.1)

### ISSUE THREAD

**Issue by sabatale** [navigateconsulting/virtual-assistant#169]
**Describe the bug**
Missing requirements show up during sudo docker-compose build:

![image](https://user-images.githubusercontent.com/50220345/79046600-fa91bd00-7bdf-11ea-9e3d-fb2eb0fd0f45.png)

**To Reproduce**
Run docker compose for the latest build on fresh install Ubuntu 18.04.

**Other**
The build works anyway and the installation finishes. However I am then unable to create a project (nothing happens after clickin "Confirm", no error in dev tools). This is likely not related though.

**Comment by saikiran2603** [comment]
sometimes socketio cases performance delays so updates show a bit late , Are you still facing the issue ?.  engineio and socketio have been pinned to those versions because both of them are dependent on each other, but yes this does not cause any issue with application functionality. let us know if u still face issue with project creation

**Comment by Beherasaptami** [comment]
any update on the above issue , i am too facing same issue with rasa 1.8 
![05 05 2020_14 35 30_REC](https://user-images.githubusercontent.com/54348413/81050656-f6ef0e80-8edd-11ea-94b5-5e8fcc7964cc.png)
how to ressolve these issue

**Comment by saikiran2603** [comment]
We are moving away from socketio in the next release, that would resolve this issue. Meanwhile the application should be functional even with this error message in the logs. Please let us know if not able to use the application .

**Comment by Beherasaptami** [comment]
Thanks for update ..and i how some doubt like how can i add stories and all

**Comment by Beherasaptami** [comment]
thanks for the update

**Comment by saikiran2603** [comment]
@Beherasaptami @sabatale This issue has been fixed now , Could you please check and revert if you see any further issues ? thanks

**Comment by sabatale** [comment]
It's working for me although some errors show up in the install logs. Thanks!

Here is what I get on fresh install with **Docker Compose 1.26.0** at **step 3/6**:

![image](https://user-images.githubusercontent.com/50220345/84180148-07525600-aa55-11ea-8058-b2e0114957c1.png)

Then **step 4/12**:

![image](https://user-images.githubusercontent.com/50220345/84180665-de7e9080-aa55-11ea-8101-109509f8ad55.png)
