### ISSUE TITLE
Some queries 

### ISSUE THREAD

**Issue by Beherasaptami** [navigateconsulting/virtual-assistant#184]
Hello there ,
I have some queries to ask like can we run multiple projects simultaneously with virtual assistant ,
we can deploy multiple projects to multiple sites ,is virtual assistant capable of handling multiple response from multiple projects .

**Comment by saikiran2603** [comment]
As of now only single project can be deployed at a time, since we are using rasa docker container as is.

**Comment by Beherasaptami** [comment]
Thanks for the update
