### ISSUE TITLE
Need to refresh browser again and again to check the updates and page navigation is not working 

### ISSUE THREAD

**Issue by Beherasaptami** [navigateconsulting/virtual-assistant#185]
I have setup virtual-assistant on local host found one issue like page navigation is not working and whenver i tried to update it's not getting updated need to refresh the page again and again for example if i created a project then it should reflect directly but here i need to refresh to get the new project on the list , same for adding intents and response as well ...

**Desktop :**
 - Browser [ chrome]
 - Version [81]

**Comment by saikiran2603** [comment]
Thanks for reporting. We are refactoring the app , it would solve the issue. next release (hopefully by weekend) should have these issues fixed .

**Comment by saikiran2603** [comment]
@Beherasaptami Recent version has this issue fixed.
