### ISSUE TITLE
api_gateway exiting with error

### ISSUE THREAD

**Issue by j-rohit-2000** [navigateconsulting/virtual-assistant#186]
Hello

I am using Ubuntu 18.04.4. Trying to spin up the development environment using the below compose files.

docker-compose -f docker-compose.devel.yml build
docker-compose -f docker-compose.devel.yml up -d

Following containers are up 
ui_trainer
mongodb

but 
api_gateway is exiting. 

Log shows the following. Can you help. 	

Traceback (most recent call last):
  File "app.py", line 8, in <module>
    if os.environ["LOGGING"] == 'Yes':
  File "/usr/local/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'LOGGING'

Thanks and Regards
Rohit

**Comment by saikiran2603** [comment]
Hi , docker-compose.devel.yml , is a bit out dated. Could you please use the docker-compose.yml , main file , and comment containers which you do not want, and build. That ways you would be able to recreate dev environment as you want. Also , the project is undergoing a major release, scheduled to get published in few days. fyi.

**Comment by saikiran2603** [comment]
@j-rohit-2000 We have pushed a new release to master. This issue has been fixed in it. Could you try it again now with docker-compose.yml.
