### ISSUE TITLE
[Release One] User unable to annotate Entity when the select extends the word's length

### ISSUE THREAD

**Issue by svarghese8** [navigateconsulting/virtual-assistant#19]
| Attributes|      Values|
|----------|:-------------:|
| Detected By |  @svarghese8 | 
| Detected On |   22/04/2019   |  
| Detected in Release | One |  
| Severity | Medium  |
| Priority | Medium|
| Module | Manage Entities |   
| Estimated Fix Time |  |
| Root Cause Analysis|  |     
| Actual Fix Time |  |  
| Closing Date |  |
| Closing Version |  |    
| Planed Closing Version | | 

**Description**

**Pre-Condition:** User should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Launch EVA ChatbotApp URL.
2. Create a User-defined Domain
3. Navigate to the Intent Page
4. Create an Entity
5. Add some user utterance
6. Select a word beyond its length to annotate

**Expected Result:** User should be able to annotate the word for an entity

**Actual Result:** The annotation popup does not get displayed and the user is unable to annotate.

![image](https://user-images.githubusercontent.com/49480607/56664463-c159f780-66c5-11e9-8846-0fd9c4885944.png)

**Comment by nishant1712** [comment]
When you try to select the word beyond its length, the mouse eliminates the text which it had selected, which causes the functionality to not work as expected.
