### ISSUE TITLE
Containers are not running 

### ISSUE THREAD

**Issue by EdukondaluK** [navigateconsulting/virtual-assistant#224]
I have pulled the code and did  docker-compose -f docker-compose.build_from_source.yml build

It is not running and didnt get the proper logs too here.

Building va_ui_trainer
Step 1/12 : FROM node:erbium-alpine as builder
ERROR: Service 'va_ui_trainer' failed to build: Error parsing reference: "node:erbium-alpine as builder" is not a valid repository/tag: invalid reference format

Kindly help so that I will start work on it continuously going forward in next 3 months please.

**Comment by saikiran2603** [comment]
@EdukondaluK have you made any change to the va_ui_trainer code base locally ? if not can you try using the docker images instead of building the code ?

**Comment by saikiran2603** [comment]
@EdukondaluK is your issue resolved ?

**Comment by EdukondaluK** [comment]
Hi,

Have done setup on windows machine.
Everything is working fine.

Thanks for your help.

Regards,
Edukondalu

**Comment by saikiran2603** [comment]
@EdukondaluK Thanks ! , could you confirm the windows version and docker / compose version as well? we would like to add it in our documentation.

**Comment by EdukondaluK** [comment]
sure...  

its windows 10 and Docker version 19.03.12, build 48a66213fe

model trained and it didnt workout  the try now option.
can you guide me where am missing configurations here

![image](https://user-images.githubusercontent.com/18613739/92396497-b7158d80-f142-11ea-9900-843514064f7a.png)

![image](https://user-images.githubusercontent.com/18613739/92396833-52a6fe00-f143-11ea-97df-679da0dbed90.png)

**Comment by saikiran2603** [comment]
Could you refresh the application once and try to train your project again ? 
Steps - 
1. Export your project 
2. Refresh the application (In applications page , you would see the refresh option )
  **This would wipe off the projects from the application** hence taking backup in step 1 
3. Import your project 
4. try to replicate the issue 

please do let us know how this goes

**Comment by EdukondaluK** [comment]
Hi Kiran,

It is working fine.I have one doubt  that how to choose entity value in intent text area.

![image](https://user-images.githubusercontent.com/18613739/92461051-5f306280-f1e6-11ea-8a4a-e1114057fb69.png)

**Comment by saikiran2603** [comment]
@EdukondaluK you can select the text with mouse to add entities value to any of the text
