### ISSUE TITLE
chatbot angular build file to deploy my webserver 

### ISSUE THREAD

**Issue by mohan570** [navigateconsulting/virtual-assistant#226]
Hi Team,

How to get Angular build file to deploy separate web server.
-- fyi - the Try now options is working fine, after the model deployment 

Regards,
Mohan

**Comment by saikiran2603** [comment]
Could you explain what are you trying to achieve or the issue ? I dont think i clearly understand your question

**Comment by mohan570** [comment]
> Could you explain what are you trying to achieve or the issue ? I dont think i clearly understand your question

Hi Saikiran,

I need to deploy the bot in web channel as angular build or html

**Comment by nishant1712** [comment]
Hi Mohan,

Use this web component, made in polymer https://github.com/navigateconsulting/web-channel , All you need to do is deploy the project that you have created and import the above component in any html and you are good to go.

Let me know if you have any queries.

Thanks

**Comment by mohan570** [comment]
> Hi @mohan570,
> 
> Use this web component, made in polymer https://github.com/navigateconsulting/web-channel , All you need to do is deploy the project that you have created and import the above component in any html and you are good to go.
> 
> Let me know if you have any queries.
> 
> Thanks

Hi Nishant,

Thanks for you support. do we have any sample for that web component in html.

**Comment by nishant1712** [comment]
Hi @mohan570,

You can create a normal html file, and add this 
<script type="module" src="https://unpkg.com/@navigateconsulting/web-channel@latest/build/default/eva-bot.js"></script>
in your <head></head> elements, once that is done and you open your html file in browser, you will see a button appearing on the bottom right of your screen. There you go, thats your chatbot component on html.
Let me know if you have any queries.

Thanks
