### ISSUE TITLE
Bot is not giving correct response

### ISSUE THREAD

**Issue by gauravshremayee** [navigateconsulting/virtual-assistant#227]
**Describe the bug**
Bot is not giving correct response

**To Reproduce**

Projects -> BaseDomain

Try Now

Say Hi to Bot

Bot is not giving correct response

**Expected behavior**

Bot should give response : Hello ! Welcome ! My name is Eva 

**Screenshots**
<img width="1265" alt="Screenshot 2020-09-09 at 10 24 25 PM" src="https://user-images.githubusercontent.com/4831448/92629110-7442e980-f2eb-11ea-853f-dcd665385ec2.png">

**Desktop (please complete the following information):**
Mac

Chrome

 84.0.4147.135
**Additional context**
NA

**Comment by EdukondaluK** [comment]
Hi Gaurav,

It is working perfectly fine for me.
can you do refresh once.. it will available on right side of menu.

thanks and regards,
edukondalu

**Comment by gauravshremayee** [comment]
Thanks @EdukondaluK  , let me try reproduce it once again.

**Comment by mohan570** [comment]
Hi @EdukondaluK , 
How to get Angular build file to deploy separate web server as web channel

**Comment by hebimonhp** [comment]
I have the same issue, need some explains

**Comment by saikiran2603** [comment]
@mohan570 @hebimonhp  Could you explain it a bit ? Are you looking to integrate the bot in a web channel ?

**Comment by mohan570** [comment]
> @mohan570 @hebimonhp Could you explain it a bit ? Are you looking to integrate the bot in a web channel ?

-- Hi Saikiran,

Yes am looking for integrate the bot in a WEB channel

**Comment by nishant1712** [comment]
Hi @mohan570 ,

Use this web component, made in polymer https://github.com/navigateconsulting/web-channel , All you need to do is deploy the project that you have created and import the above component in any html and you are good to go.

Let me know if you have any queries.

Thanks

**Comment by mohan570** [comment]
> Hi @mohan570 ,
> 
> Use this web component, made in polymer https://github.com/navigateconsulting/web-channel , All you need to do is deploy the project that you have created and import the above component in any html and you are good to go.
> 
> Let me know if you have any queries.
> 
> Thanks

Hi Nishant,

Thanks for you support. do we have any sample for that web component in html.

**Comment by nishant1712** [comment]
Hi @mohan570,

You can create a normal html file, and add this 
<script type="module" src="https://unpkg.com/@navigateconsulting/web-channel@latest/build/default/eva-bot.js"></script>
in your <head></head> elements, once that is done and you open your html file in browser, you will see a button appearing on the bottom right of your screen. There you go, thats your chatbot component on html.
Let me know if you have any queries.

Thanks
