### ISSUE TITLE
Hi Kiran,

### ISSUE THREAD

**Issue by EdukondaluK** [navigateconsulting/virtual-assistant#228]
Hi Kiran,

It is working fine.I have one doubt  that how to choose entity value in intent text area.

![image](https://user-images.githubusercontent.com/18613739/92461051-5f306280-f1e6-11ea-8a4a-e1114057fb69.png)

_Originally posted by @EdukondaluK in https://github.com/navigateconsulting/virtual-assistant/issues/224#issuecomment-688754470_

**Comment by saikiran2603** [comment]
@EdukondaluK you can select the text with mouse to add entities value to any of the text
