### ISSUE TITLE
[Release One]Search option is not available on Manage Entity Page.

### ISSUE THREAD

**Issue by svarghese8** [navigateconsulting/virtual-assistant#27]
| Attributes|      Values|
|----------|:-------------:|
| Detected By |  @svarghese8 | 
| Detected On |   06/05/2019   |  
| Detected in Release | One |  
| Severity |High  |
| Priority |High |
| Module | Manage Entities|   
| Estimated Fix Time |  |
| Root Cause Analysis|  |     
| Actual Fix Time |  |  
| Closing Date |  |
| Closing Version |  |    
| Planed Closing Version | | 

**Description**

**Pre-Condition:** User should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Launch EVA ChatbotApp URL.
2. Create a User-defined Domain
3. Create few intents
4. Create few entities
5. Search for an entity

**Expected Result:** User should be able to search for the entities from the given page.

**Actual Result:** No Search option is displayed.

![image](https://user-images.githubusercontent.com/49480607/60587001-ff078a80-9db0-11e9-98ba-8e98775ff7a9.png)

**Comment by saikiran2603** [comment]
Issue fixed
