### ISSUE TITLE
[Release One]'Train' and 'Restore' buttons are to be added

### ISSUE THREAD

**Issue by svarghese8** [navigateconsulting/virtual-assistant#28]
Train EVA: This feature allows the user to train EVA once the artifacts are being fed into. NLU Model gets trained as per the data provided and the changes made to the assistant should be reflected.  On clicking on ‘Train’ the entire Model gets trained along with all the domains present.

Restore: This button allows to restore the EVA to its initial stage. Once the user has made changes to EVA at any point, this feature allows the user to restore the assistant to its initial stage. Once restored all the data that is entered into the assistant by the user will be wiped out and only the default domains with its default intent, entities and stories will be present in EVA

**Comment by saikiran2603** [comment]
Resolved.
