### ISSUE TITLE
[Release One][Intermittent] New project is not displayed default on it's creation even when the notification for successsful creation is displayed

### ISSUE THREAD

**Issue by svarghese8** [navigateconsulting/virtual-assistant#51]
| Attributes|      Values|
|----------|:-------------:|
| Detected By |  @svarghese8 | 
| Detected On |   03/07/2019   |  
| Detected in Release | One |  
| Severity |Medium  |
| Priority |Medium |
| Module | Manage Project/Intent/Domain/Response/Story/Entity|   
| Estimated Fix Time |  |
| Root Cause Analysis|  |     
| Actual Fix Time |  |  
| Closing Date |  |
| Closing Version |  |    
| Planed Closing Version | | 

**Description**

**Pre-Condition:** User should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Access EVA
2. Click on 'Add project'
3. Give a project name and description
4. Click on Confirm

**Expected Result:** Project should be successfully created and should be displayed. Notification should be displayed as well.

**Actual Result:** Project is created and notification is displayed as well. However, the project is not displayed in the project list and needs a refresh to be displayed in the project list table.

![image](https://user-images.githubusercontent.com/49480607/60598584-90cfc180-9dca-11e9-86ea-022ee9caa851.png)

![image](https://user-images.githubusercontent.com/49480607/60598598-9927fc80-9dca-11e9-9148-04fb0b78dd22.png)

![image](https://user-images.githubusercontent.com/49480607/60598614-9cbb8380-9dca-11e9-9a7b-3fcabfb9584b.png)

![image](https://user-images.githubusercontent.com/49480607/60598624-a2b16480-9dca-11e9-9149-aa360092b5fe.png)

**Comment by nishant1712** [comment]
This issue is not reproducible as the socket io mechanism depends on the network. If the network is lagging, then the expected result would delay for a bit. Refreshing the page fixes the issue in such case.
