### ISSUE TITLE
[Release One][intermittent]Not able to see newly created entity without Refresh.

### ISSUE THREAD

**Issue by karishmabodhane** [navigateconsulting/virtual-assistant#53]
| Attributes|      Values|
|----------|:-------------:|
| Detected By |  @karishmabodhane | 
| Detected On |   03/07/2019   |  
| Detected in Release | One |  
| Severity |Critical  |
| Priority |High |
| Module | Manage Entities|   
| Estimated Fix Time |  |
| Root Cause Analysis|  |     
| Actual Fix Time |  |  
| Closing Date |  |
| Closing Version |  |    
| Planed Closing Version | | 

**Description**

**Pre-Condition:** User should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Launch EVA ChatbotApp URL.
2. Select a project.
3. Click on add entity.
4. Add entity name provide description and type.
5. Refresh the page.

**Expected Result:** Newly added entity should be display without refresh.

**Actual Result:** Not displaying newly added entity without refresh.

![image](https://user-images.githubusercontent.com/47655741/60603183-dee8c300-9dd2-11e9-9c9f-fa9e618437b2.png)

![image](https://user-images.githubusercontent.com/47655741/60602886-4f431480-9dd2-11e9-8d57-5aca469416b0.png)

**Comment by saikiran2603** [comment]
Not a code issue
