### ISSUE TITLE
[Release One]User should be able to see values for entity.

### ISSUE THREAD

**Issue by karishmabodhane** [navigateconsulting/virtual-assistant#56]
| Attributes|      Values|
|----------|:-------------:|
| Detected By |  @karishmabodhane  | 

**Description**

**Pre-Condition:** User should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Launch EVA ChatbotApp URL.
2. Click on trainer icon.
3. Select a project.
4. Create an entity.
5. Select the same entity.

**Expected Result:** User should be able to see stored entity values.

![image](https://user-images.githubusercontent.com/47655741/60645081-62e38f00-9e55-11e9-8303-a1ee01ffc6e6.png)

**Comment by saikiran2603** [comment]
Values would be visible for categorical type entity
