### ISSUE TITLE
[Release One]Unable to train the project,the process takes lot of time.

### ISSUE THREAD

**Issue by karishmabodhane** [navigateconsulting/virtual-assistant#57]
| Attributes|      Values|
|----------|:-------------:|
| Detected By |  @karishmabodhane  | 
| Detected On |   04/07/2019   |  
| Detected in Release | One |  
| Severity |Critical  |
| Priority |High |
| Module | Manage Project|   
| Estimated Fix Time |  |
| Root Cause Analysis|  |     
| Actual Fix Time |  |  
| Closing Date |  |
| Closing Version |  |    
| Planed Closing Version | | 

**Description**

**Pre-Condition:** User should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Launch EVA ChatbotApp URL.
2. select try now icon of base project.

**Expected Result:** Eva should be trained in acceptable amount of time and Try now page should be display .

**Actual Result:** It is taking a lot of time.

![image](https://user-images.githubusercontent.com/47655741/60650241-63822280-9e61-11e9-8d5d-7ff19e6ff2fc.png)

**Comment by saikiran2603** [comment]
Resolved now .
