### ISSUE TITLE
[Release One]Delete user utterence does not display confirmation/ success message.

### ISSUE THREAD

**Issue by karishmabodhane** [navigateconsulting/virtual-assistant#62]
| Attributes|      Values|
|----------|:-------------:|
| Detected By |  @karishmabodhane  | 
| Detected On |   04/07/2019   |  
| Detected in Release | One |  
| Severity |Medium  |
| Priority |Medium |
| Module | Manage Stories|   
| Estimated Fix Time |  |
| Root Cause Analysis|  |     
| Actual Fix Time |  |  
| Closing Date |  |
| Closing Version |  |    
| Planed Closing Version | | 

**Description**

**Pre-Condition:** User should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Launch EVA ChatbotApp URL.
2. Select a project which is already trained.
3. Select a story.
4. delete a node.

**Expected Result:** After deleting a story node it should diaplay a confirmation message .

**Actual Result:** After deleting a story node it is not displaying confirmation message and node get deleted.

![image](https://user-images.githubusercontent.com/47655741/60655598-a517cb00-9e6b-11e9-8867-4ccaa2315736.png)

**Comment by nishant1712** [comment]
Displaying deleting confirmation message on the stories page will become too cumbersome and bombard the page with lot of messages on each intent/response node delete respectively.
