### ISSUE TITLE
[Release One]Able to delete base default Project

### ISSUE THREAD

**Issue by svarghese8** [navigateconsulting/virtual-assistant#64]
| Attributes|      Values|
|----------|:-------------:|
| Detected By |  @svarghese8 | 
| Detected On |   04/07/2019   |  
| Detected in Release | One |  
| Severity |High  |
| Priority |High |
| Module | Manage Project|   
| Estimated Fix Time |  |
| Root Cause Analysis|  |     
| Actual Fix Time |  |  
| Closing Date |  |
| Closing Version |  |    
| Planed Closing Version | | 

**Description**

**Pre-Condition:** User should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Launch EVA ChatbotApp URL.
2. Navigate to the Base project
3. Click on Delete

**Expected Result:** Error Message Should be displayed stating base project cannot be displayed.

**Actual Result:** User is able to delete Base project

![image](https://user-images.githubusercontent.com/49480607/60662726-cc29c900-9e7a-11e9-8f58-8d5f8341b00a.png)

![image](https://user-images.githubusercontent.com/49480607/60662736-d0ee7d00-9e7a-11e9-80cb-6e44df94b918.png)

![image](https://user-images.githubusercontent.com/49480607/60662767-e2378980-9e7a-11e9-9128-2efcc9165660.png)

**Comment by saikiran2603** [comment]
Expected functionality
