### ISSUE TITLE
[Release One]Able to delete template project, domain and stories.

### ISSUE THREAD

**Issue by karishmabodhane** [navigateconsulting/virtual-assistant#69]
| Attributes|      Values|
|----------|:-------------:|
| Detected By |  @karishmabodhane  | 
| Detected On |   05/07/2019   |  
| Detected in Release | One |  
| Severity |High  |
| Priority |High |
| Module | Manage Project|   
| Estimated Fix Time |  |
| Root Cause Analysis|  |     
| Actual Fix Time |  |  
| Closing Date |  |
| Closing Version |  |    
| Planed Closing Version | | 

**Description**

**Pre-Condition:** User should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Launch EVA ChatbotApp URL.
2. select story tab of base project and click on delete icon.
3. Select Domain tab and try to delete domain.
4. Select project tab and try to delete base project.

**Expected Result:** Base project , domains, intent, response, story, entity should not be deletable.
**Actual Result:** Able to delete base project, domain and story.

* Able to delete story::
![image](https://user-images.githubusercontent.com/47655741/60717722-5ab44e00-9f40-11e9-8ce9-da4e5e20ded0.png)

* Able to delete base domain::

![image](https://user-images.githubusercontent.com/47655741/60718143-82f07c80-9f41-11e9-8ff0-c27e17875905.png)

*Able to delete base project.
![image](https://user-images.githubusercontent.com/47655741/60718220-bb905600-9f41-11e9-9a40-343a2c12f976.png)

**Comment by saikiran2603** [comment]
Expected functionality
