### ISSUE TITLE
[Release One]Unable to Edit User Utterance

### ISSUE THREAD

**Issue by svarghese8** [navigateconsulting/virtual-assistant#71]
| Attributes|      Values|
|----------|:-------------:|
| Detected By |  @svarghese8 | 
| Detected On |   05/07/2019   |  
| Detected in Release | One |  
| Severity |Medium  |
| Priority |Medium |
| Module | Manage Intent|   
| Estimated Fix Time |  |
| Root Cause Analysis|  |     
| Actual Fix Time |  |  
| Closing Date |  |
| Closing Version |  |    
| Planed Closing Version | | 

**Description**

**Pre-Condition:** User should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Launch EVA ChatbotApp URL.
2. Click on Create Project
2. Create  a domain and add an Intent
3. Add few User utterances
4. Navigate away from the page.
5. Navigate to the Intent created in step 2
6. Try to edit a user utterance added as a part of step 3

**Expected Result:** User should be able to edit the user utterance

**Actual Result:**  User is unable to Edit the User Utterance

![image](https://user-images.githubusercontent.com/49480607/60718815-66edda80-9f43-11e9-8c57-3758b607582b.png)

**Comment by saikiran2603** [comment]
No edit mode at this point .
