### ISSUE TITLE
[Release One]Back button navigates to the landing page instead of previous page.

### ISSUE THREAD

**Issue by karishmabodhane** [navigateconsulting/virtual-assistant#78]
| Attributes|      Values|
|----------|:-------------:|
| Detected By |  @karishmabodhane  | 
| Detected On |   09/07/2019   |  
| Detected in Release | One |  
| Severity |Medium  |
| Priority |Medium |
| Module | Manage EVA|   
| Estimated Fix Time |  |
| Root Cause Analysis|  |     
| Actual Fix Time |  |  
| Closing Date |  |
| Closing Version |  |    
| Planed Closing Version | | 

**Description**

**Pre-Condition:** User should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Launch EVA ChatbotApp URL.
2. select a project and enter inside a domain.
3. click on the back button.

**Expected Result:**It should redirect control to the previous page.
**Actual Result:** It navigates to the landing page.

Before:
![image](https://user-images.githubusercontent.com/47655741/60885296-e2fe6000-a26c-11e9-9b57-2dd71d7bcd7c.png)

After clicked on back button:
![image](https://user-images.githubusercontent.com/47655741/60885327-f90c2080-a26c-11e9-8690-0f8887e70f11.png)

**Comment by nishant1712** [comment]
As the main URL where the application is rendered is a single page app. So the browser on clicking on back button will navigate to the browser's previous URL (which can be anything). Breadcrumb functionality has been provided to ease the navigation within the app.
