### ISSUE TITLE
[Release One]Artifacts names are not editable.

### ISSUE THREAD

**Issue by karishmabodhane** [navigateconsulting/virtual-assistant#80]
| Attributes|      Values|
|----------|:-------------:|
| Detected By |  @karishmabodhane  | 

**Description**

**Pre-Condition:** User should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Launch EVA ChatbotApp URL.
2. Select a project.
3. Try to edit intent name, response name, story name, domain name and entity name.

**Expected Result:** Allow user to edit artifact name.

**Comment by saikiran2603** [comment]
Expected functionlaity
