### ISSUE TITLE
[Release One]While creating story at least one intent and response node is nessesary.

### ISSUE THREAD

**Issue by karishmabodhane** [navigateconsulting/virtual-assistant#87]
| Attributes|      Values|
|----------|:-------------:|
| Detected By |  @karishmabodhane  | 
| Detected On |   10/07/2019   |  
| Detected in Release | One |  
| Severity |Medium  |
| Priority |Medium |
| Module | Manage Story|   
| Estimated Fix Time |  |
| Root Cause Analysis|  |     
| Actual Fix Time |  |  
| Closing Date |  |
| Closing Version |  |    
| Planed Closing Version | | 

**Description**

**Pre-Condition:** User should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Launch EVA ChatbotApp URL.
2. select a project and domain.
3. Select story tab.

**Expected Result:** Eva should display one intent and response node as default one .

**Actual Result:** Eva is displaying only default intent node not response node.

![image](https://user-images.githubusercontent.com/47655741/60957777-dccabb00-a322-11e9-8b63-434559bd9831.png)

**Comment by saikiran2603** [comment]
Shows informative error messages now closing the issue
