### ISSUE TITLE
[Release One]Unable to add '@' in response value.

### ISSUE THREAD

**Issue by karishmabodhane** [navigateconsulting/virtual-assistant#91]
| Attributes|      Values|
|----------|:-------------:|
| Detected By |  @karishmabodhane  | 
| Detected On |   11/07/2019   |  
| Detected in Release | One |  
| Severity |Medium  |
| Priority |Medium |
| Module | Manage Response|   
| Estimated Fix Time |  |
| Root Cause Analysis|  |     
| Actual Fix Time |  |  
| Closing Date |  |
| Closing Version |  |    
| Planed Closing Version | | 

**Description**

**Pre-Condition:** User should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Launch EVA ChatbotApp URL.
2. select a project and domain.
3. Select response tab.
4. Enter @  as a value  in response value field.

**Expected Result:** Eva should allow me to enter @ as a text in response value.

**Actual Result:** I am unable to enter @ as a text and list of entities are displayed.

![image](https://user-images.githubusercontent.com/47655741/61033649-896b7200-a3e1-11e9-953e-c00dd837c7cd.png)

**Comment by nishant1712** [comment]
This issue has been resolved. Earlier '@' was responsible for populating entities to map with the repsonses, now instead of '@', the key '{' is used to populate entities.
