### ISSUE TITLE
[Release One]Able to delete User utterence and response value even when mapped to a story.

### ISSUE THREAD

**Issue by karishmabodhane** [navigateconsulting/virtual-assistant#92]
| Attributes|      Values|
|----------|:-------------:|
| Detected By |  @karishmabodhane  | 
| Detected On |   11/07/2019   |  
| Detected in Release | One |  
| Severity |Medium  |
| Priority |High |
| Module | Manage Intent, Manage Response|   
| Estimated Fix Time |  |
| Root Cause Analysis|  |     
| Actual Fix Time |  |  
| Closing Date |  |
| Closing Version |  |    
| Planed Closing Version | | 

**Description**

**Pre-Condition:** User should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Launch EVA ChatbotApp URL.
2. select a project and domain.
3. Select created story and see the intent and response values used in story.
4. Select intent tab and delete same value which is used in story.
5. Select response tab and delete same response value which is used in story.

**Expected Result:** Eva should not allow to delete user utterences.

**Actual Result:** Eva allowing me to delete user utterences.

User utterences mapped to a story:
![image](https://user-images.githubusercontent.com/47655741/61034947-df411980-a3e3-11e9-9f92-1e8a003b66bd.png)

Before deleting user utterence in intent tab:
![image](https://user-images.githubusercontent.com/47655741/61035088-23341e80-a3e4-11e9-9524-3024377c4f4c.png)

After deleting user utterence:
![image](https://user-images.githubusercontent.com/47655741/61035118-30e9a400-a3e4-11e9-99bc-3bd2df957c48.png)

Before deleting response value:
![image](https://user-images.githubusercontent.com/47655741/61035155-419a1a00-a3e4-11e9-973d-5b6f8df57ee1.png)

After deleting response value:
![image](https://user-images.githubusercontent.com/47655741/61035178-524a9000-a3e4-11e9-83c2-2ee7fd0c2cb4.png)

**Comment by saikiran2603** [comment]
Issue fixed
