### ISSUE TITLE
[Release One][Mozila FF] When adding entity to intent, after adding error is displayed.

### ISSUE THREAD

**Issue by karishmabodhane** [navigateconsulting/virtual-assistant#96]
| Attributes|      Values|
|----------|:-------------:|
| Detected By |  @karishmabodhane  | 
| Detected On |   12/07/2019   |  
| Detected in Release | One |  
| Severity |Medium  |
| Priority |Medium |
| Module | Manage Stories|   
| Estimated Fix Time |  |
| Root Cause Analysis|  |     
| Actual Fix Time |  |  
| Closing Date |  |
| Closing Version |  |    
| Planed Closing Version | | 

**Description**

**Pre-Condition:** User should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Launch EVA ChatbotApp URL.
2. create a new project
3. Create a new domain and add few intents, entities and stories
4, Create a story
5. Enter a value for the intent node
6.Expand the Intent node to provide entity details.
7. Type in the name of the entity to  be added.
8. Type in the value of the entity
9. click on confirm

**Expected Result:** Entity value should be added and the typed in entity name should disappear from the add entity textbox

**Actual Result:** Entity value is added to the node, however the entity name does not disappear from the add entity textbox and an erroe is displayed as shown in the screenshot. User has to explicitly remove the entered entity name.

![image](https://user-images.githubusercontent.com/47655741/61126980-8e0c5500-a4cb-11e9-9771-4979cf3d753d.png)

![image](https://user-images.githubusercontent.com/47655741/61126992-95336300-a4cb-11e9-90ab-26f46b2904ee.png)

**Comment by saikiran2603** [comment]
Resolved
