### ISSUE TITLE
[Release One]On deletion of node( intent and response) from story page, it should display confirmation message.

### ISSUE THREAD

**Issue by karishmabodhane** [navigateconsulting/virtual-assistant#98]
| Attributes|      Values|
|----------|:-------------:|
| Detected By |  @karishmabodhane  | 
| Detected On |   15/07/2019   |  
| Detected in Release | One |  
| Severity |Medium |
| Priority |Medium |
| Module | Manage Story|   
| Estimated Fix Time |  |
| Root Cause Analysis|  |     
| Actual Fix Time |  |  
| Closing Date |  |
| Closing Version |  |    
| Planed Closing Version | | 

**Description**

**Pre-Condition:** User should have access to EVA.

**Steps To Reproduce:** Steps to reproduce are
1. Launch EVA ChatbotApp URL.
2. Create a project and domain.
3. Create a story with the help of intent and responses.
4. Delete a node from created story.

**Expected Result:** Eva should display a confirmation message on deletion of nodes .

**Actual Result:** It is not displaying any confirmation message.

Go to story page :
![image](https://user-images.githubusercontent.com/47655741/61205014-88518200-a70c-11e9-9ff9-4bad248eb2e2.png)

Delete a node from story:
![image](https://user-images.githubusercontent.com/47655741/61205021-90a9bd00-a70c-11e9-9829-935836a66941.png)

**Comment by nishant1712** [comment]
Displaying deleting confirmation message on the stories page will become too cumbersome and bombard the page with lot of messages on each intent/response node delete respectively.
